<?php

namespace Database\Factories\Accounts;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Accounts\AccountTransfer>
 */
class AccountTransferFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'date' => $this->faker->dateTimeBetween('-30 days', 'now'),
            // code is auto-generated by the model
            // prefix is set by default in migration
            'prefix' => 'TRF',
            'from_account_id' => \App\Models\Accounts\Account::factory(),
            'to_account_id' => \App\Models\Accounts\Account::factory(),
            'from_currency_id' => \App\Models\Setups\Generals\Currencies\Currency::factory(),
            'to_currency_id' => \App\Models\Setups\Generals\Currencies\Currency::factory(),
            'received_amount' => $this->faker->randomFloat(2, 100, 10000),
            'sent_amount' => $this->faker->randomFloat(2, 100, 10000),
            'currency_rate' => $this->faker->randomFloat(4, 0.5, 2.0),
            'note' => $this->faker->optional(0.6)->sentence(),
        ];
    }
}
