<?php

namespace Database\Factories\Suppliers;

use App\Models\Setups\Generals\Currencies\Currency;
use App\Models\Setups\Supplier;
use App\Models\Setups\Warehouse;
use App\Models\Suppliers\PurchaseReturn;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Suppliers\PurchaseReturn>
 */
class PurchaseReturnFactory extends Factory
{
    protected $model = PurchaseReturn::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $subTotal = $this->faker->randomFloat(2, 100, 10000);
        $shippingFee = $this->faker->randomFloat(2, 0, 500);
        $customsFee = $this->faker->randomFloat(2, 0, 300);
        $otherFee = $this->faker->randomFloat(2, 0, 100);
        $taxAmount = $this->faker->randomFloat(2, 0, $subTotal * 0.15);
        $additionalCharge = $this->faker->randomFloat(2, 0, $subTotal * 0.05);

        $finalTotal = $subTotal + $shippingFee + $customsFee + $otherFee + $taxAmount + $additionalCharge;

        return [
            // 'code' will be auto-generated by the model
            'date' => $this->faker->dateTimeBetween('-6 months', 'now'),
            'shipping_status' => $this->faker->randomElement(['Waiting', 'Shipped', 'Delivered']),
            'supplier_id' => Supplier::first()?->id ?? Supplier::factory(),
            'warehouse_id' => Warehouse::first()?->id ?? Warehouse::factory(),
            'currency_id' => Currency::first()?->id ?? Currency::factory(),
            'supplier_purchase_return_number' => $this->faker->unique()->regexify('RET-[A-Z]{2,3}-[0-9]{4,6}'),
            'currency_rate' => $this->faker->randomFloat(6, 0.5, 2.0),

            // Fees in USD
            'shipping_fee_usd' => $shippingFee,
            'customs_fee_usd' => $customsFee,
            'other_fee_usd' => $otherFee,
            'tax_usd' => $taxAmount,

            // Percentage fees (alternative to fixed fees)
            'shipping_fee_usd_percent' => $this->faker->randomFloat(2, 0, 15),
            'customs_fee_usd_percent' => $this->faker->randomFloat(2, 0, 10),
            'other_fee_usd_percent' => $this->faker->randomFloat(2, 0, 5),
            'tax_usd_percent' => $this->faker->randomFloat(2, 0, 15),

            // Totals
            'sub_total' => $subTotal,
            'sub_total_usd' => $subTotal,
            'additional_charge_amount' => $additionalCharge,
            'additional_charge_amount_usd' => $additionalCharge,
            'total' => $subTotal + $additionalCharge,
            'total_usd' => $subTotal + $additionalCharge,
            'final_total' => $finalTotal,
            'final_total_usd' => $finalTotal,

            'note' => $this->faker->optional(0.6)->sentence(),
            'created_by' => User::factory(),
            'updated_by' => function (array $attributes) {
                return $this->faker->boolean(30) ? User::factory() : $attributes['created_by'];
            },
        ];
    }

    /**
     * Purchase return with minimal required fields only
     */
    public function minimal(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_fee_usd' => 0,
            'customs_fee_usd' => 0,
            'other_fee_usd' => 0,
            'tax_usd' => 0,
            'shipping_fee_usd_percent' => 0,
            'customs_fee_usd_percent' => 0,
            'other_fee_usd_percent' => 0,
            'tax_usd_percent' => 0,
            'additional_charge_amount' => 0,
            'additional_charge_amount_usd' => 0,
            'shipping_status' => null,
            'note' => null,
        ]);
    }

    /**
     * Purchase return with high shipping costs
     */
    public function withHighShipping(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_fee_usd' => $this->faker->randomFloat(2, 500, 2000),
            'shipping_fee_usd_percent' => $this->faker->randomFloat(2, 10, 25),
        ]);
    }

    /**
     * Purchase return with additional charges
     */
    public function withAdditionalCharges(): static
    {
        return $this->state(function (array $attributes) {
            $additionalCharge = $attributes['sub_total'] * $this->faker->randomFloat(2, 0.05, 0.15);
            return [
                'additional_charge_amount' => $additionalCharge,
                'additional_charge_amount_usd' => $additionalCharge,
                'total' => $attributes['sub_total'] + $additionalCharge,
                'total_usd' => $attributes['sub_total_usd'] + $additionalCharge,
            ];
        });
    }

    /**
     * Purchase return in foreign currency
     */
    public function foreignCurrency(): static
    {
        return $this->state(function (array $attributes) {
            $rate = $this->faker->randomFloat(6, 0.7, 1.5);
            return [
                'currency_rate' => $rate,
                'sub_total' => $attributes['sub_total_usd'] * $rate,
                'total' => $attributes['total_usd'] * $rate,
                'final_total' => $attributes['final_total_usd'] * $rate,
            ];
        });
    }

    /**
     * Recent purchase return (last 30 days)
     */
    public function recent(): static
    {
        return $this->state(fn (array $attributes) => [
            'date' => $this->faker->dateTimeBetween('-30 days', 'now'),
        ]);
    }

    /**
     * Large purchase return
     */
    public function large(): static
    {
        return $this->state(function (array $attributes) {
            $subTotal = $this->faker->randomFloat(2, 50000, 200000);
            $finalTotal = $subTotal + $this->faker->randomFloat(2, 1000, 5000);

            return [
                'sub_total' => $subTotal,
                'sub_total_usd' => $subTotal,
                'total' => $subTotal,
                'total_usd' => $subTotal,
                'final_total' => $finalTotal,
                'final_total_usd' => $finalTotal,
            ];
        });
    }

    /**
     * Waiting for shipment
     */
    public function waiting(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_status' => 'Waiting',
        ]);
    }

    /**
     * Shipped
     */
    public function shipped(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_status' => 'Shipped',
        ]);
    }

    /**
     * Delivered
     */
    public function delivered(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_status' => 'Delivered',
        ]);
    }
}
