<?php

namespace App\Imports;

use App\Models\Customers\Customer;
use App\Models\Customers\CustomerCreditDebitNote;
use App\Models\Setups\Customers\CustomerType;
use App\Models\Setups\Customers\CustomerGroup;
use App\Models\Setups\Customers\CustomerProvince;
use App\Models\Setups\Customers\CustomerZone;
use App\Models\Setups\Customers\CustomerPaymentTerm;
use App\Models\Employees\Employee;
use App\Models\Items\PriceList;
use App\Models\Setting;
use App\Helpers\CurrencyHelper;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Carbon;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithValidation;
use Maatwebsite\Excel\Concerns\WithBatchInserts;
use Maatwebsite\Excel\Concerns\WithChunkReading;

class CustomersImport implements ToCollection, WithHeadingRow, WithBatchInserts, WithChunkReading
{
    protected $skipDuplicates;
    protected $updateExisting;
    protected $results = [
        'total' => 0,
        'imported' => 0,
        'updated' => 0,
        'skipped' => 0,
        'errors' => []
    ];

    public function __construct($skipDuplicates = false, $updateExisting = false)
    {
        $this->skipDuplicates = $skipDuplicates;
        $this->updateExisting = $updateExisting;
    }

    /**
     * Process each collection/chunk
     */
    public function collection(Collection $rows)
    {
        foreach ($rows as $index => $row) {
            $this->results['total']++;
            $rowNumber = $index + 2; // +2 because of header row and 0-based index

            try {
                // Validate row data
                $result = $this->validateRow($row->toArray(), $rowNumber);

                if (isset($result['error'])) {
                    $this->results['skipped']++;
                    $this->results['errors'][] = [
                        'row' => $rowNumber,
                        'error' => $result['error']
                    ];
                    continue;
                }

                $validatedData = $result['data'];
                $startingBalance = $result['starting_balance'] ?? null;

                // Check for duplicates by code only (allow duplicate names)
                $existingCustomer = null;
                if (!empty($validatedData['code'])) {
                    $existingCustomer = Customer::withTrashed()->where('code', $validatedData['code'])->first();
                }

                // Handle duplicate logic
                if ($existingCustomer) {
                    if ($this->updateExisting) {
                        // Update existing customer — never overwrite system-calculated fields
                        unset($validatedData['current_balance']);
                        $existingCustomer->update($validatedData);
                        $this->results['updated']++;

                        // Don't create starting balance for updated customers
                    } else {
                        // Skip duplicate
                        $this->results['skipped']++;
                        $this->results['errors'][] = [
                            'row' => $rowNumber,
                            'error' => "Customer already exists with code: {$validatedData['code']}"
                        ];
                    }
                } else {
                    // Create new customer
                    // If code is not provided, it will be auto-generated by the model
                    if (empty($validatedData['code'])) {
                        unset($validatedData['code']);
                    }

                    $customer = Customer::create($validatedData);
                    $this->results['imported']++;

                    // Create credit/debit note for starting balance if provided
                    if ($startingBalance !== null && $startingBalance != 0) {
                        $this->createStartingBalanceNote($customer, $startingBalance, $rowNumber);
                    }
                }

            } catch (\Exception $e) {
                $this->results['skipped']++;
                $this->results['errors'][] = [
                    'row' => $rowNumber,
                    'error' => $e->getMessage()
                ];
                Log::error("Row {$rowNumber} processing failed", [
                    'error' => $e->getMessage(),
                    'file' => $e->getFile(),
                    'line' => $e->getLine()
                ]);
            }
        }
    }

    /**
     * Validate and transform row data.
     * Only mandatory fields (*) are required. Optional fields are included only when present and non-empty.
     */
    protected function validateRow(array $row, int $rowNumber): array
    {
        // Extract starting balance separately — not stored as a column
        $startingBalance = $this->cleanNumeric($row['starting_balance'] ?? $row['opening_balance'] ?? null);

        // ── Mandatory fields ────────────────────────────────────────────────
        $data = [
            'current_balance' => 0, // always 0 on create; stripped on update
        ];

        $name = $row['name'] ?? $row['customer_name'] ?? null;
        if (empty($name)) {
            return ['error' => 'Customer name is required'];
        }
        $data['name'] = $name;

        $city = $row['city'] ?? null;
        if (empty($city)) {
            return ['error' => 'City is required'];
        }
        $data['city'] = $city;

        $mobile = $row['mobile'] ?? $row['mobile_number'] ?? null;
        if (empty($mobile)) {
            return ['error' => 'Mobile is required'];
        }
        $data['mobile'] = $mobile;

        // customer_type (mandatory lookup)
        $typeName = $row['customer_type'] ?? $row['type'] ?? null;
        if (empty($typeName)) {
            return ['error' => 'Customer type is required'];
        }
        $customerType = CustomerType::where('name', $typeName)->first();
        if (!$customerType) {
            return ['error' => "Customer type '{$typeName}' not found"];
        }
        $data['customer_type_id'] = $customerType->id;

        // salesperson (mandatory lookup)
        $salespersonIdentifier = $row['salesperson'] ?? $row['salesperson_code'] ?? null;
        if (empty($salespersonIdentifier)) {
            return ['error' => 'Salesperson is required'];
        }
        $salesperson = Employee::where('code', $salespersonIdentifier)
            ->orWhere('name', $salespersonIdentifier)
            ->first();
        if (!$salesperson) {
            return ['error' => "Salesperson '{$salespersonIdentifier}' not found"];
        }
        $data['salesperson_id'] = $salesperson->id;

        // price_list_inv_code (mandatory lookup)
        $priceListInvCode = $row['price_list_inv_code'] ?? $row['price_list_code_inv'] ?? null;
        if (empty($priceListInvCode)) {
            return ['error' => 'Price list INV code is required'];
        }
        $priceListInv = PriceList::where('code', $priceListInvCode)->first();
        if (!$priceListInv) {
            return ['error' => "Price list INV '{$priceListInvCode}' not found"];
        }
        $data['price_list_id_INV'] = $priceListInv->id;

        // price_list_inx_code (mandatory lookup)
        $priceListInxCode = $row['price_list_inx_code'] ?? $row['price_list_code_inx'] ?? null;
        if (empty($priceListInxCode)) {
            return ['error' => 'Price list INX code is required'];
        }
        $priceListInx = PriceList::where('code', $priceListInxCode)->first();
        if (!$priceListInx) {
            return ['error' => "Price list INX '{$priceListInxCode}' not found"];
        }
        $data['price_list_id_INX'] = $priceListInx->id;

        // ── Optional fields — only included when present and non-empty ──────

        $code = $row['code'] ?? $row['customer_code'] ?? null;
        if (!empty($code)) {
            $data['code'] = $code;
        }

        $address = $row['address'] ?? null;
        if (!empty($address)) {
            $data['address'] = $address;
        }

        $telephone = $row['telephone'] ?? $row['phone'] ?? null;
        if (!empty($telephone)) {
            $data['telephone'] = $telephone;
        }

        $url = $row['website'] ?? $row['url'] ?? null;
        if (!empty($url)) {
            if (!filter_var($url, FILTER_VALIDATE_URL)) {
                return ['error' => 'Invalid URL format'];
            }
            $data['url'] = $url;
        }

        $googleMap = $row['google_map_link'] ?? $row['google_map'] ?? null;
        if (!empty($googleMap)) {
            $data['google_map'] = $googleMap;
        }

        $email = $row['email'] ?? null;
        if (!empty($email)) {
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
                return ['error' => 'Invalid email format'];
            }
            $data['email'] = $email;
        }

        $contactName = $row['contact_name'] ?? $row['contact'] ?? null;
        if (!empty($contactName)) {
            $data['contact_name'] = $contactName;
        }

        $gps = $row['gps_coordinates'] ?? $row['gps'] ?? null;
        if (!empty($gps)) {
            $data['gps_coordinates'] = $gps;
        }

        $mofTax = $row['mof_tax_number'] ?? $row['tax_number'] ?? null;
        if (!empty($mofTax)) {
            $data['mof_tax_number'] = $mofTax;
        }

        $notes = $row['notes'] ?? $row['remarks'] ?? null;
        if (!empty($notes)) {
            $data['notes'] = $notes;
        }

        $createdAt = $this->parseDate($row['created_at'] ?? null);
        if ($createdAt !== null) {
            $data['created_at'] = $createdAt;
        }

        $creditLimit = $this->cleanNumeric($row['credit_limit'] ?? null);
        if ($creditLimit !== null) {
            $data['credit_limit'] = $creditLimit;
        }

        $discount = $this->cleanNumeric($row['discount_percentage'] ?? $row['discount'] ?? null);
        if ($discount !== null) {
            $data['discount_percentage'] = $discount;
        }

        $totalOldSales = $this->cleanNumeric($row['total_old_sales'] ?? null);
        if ($totalOldSales !== null) {
            $data['total_old_sales'] = $totalOldSales;
        }

        if (isset($row['is_active']) && $row['is_active'] !== '' && $row['is_active'] !== null) {
            $data['is_active'] = filter_var($row['is_active'], FILTER_VALIDATE_BOOLEAN);
        }

        // Optional lookups — skipped if column is absent or empty
        $groupName = $row['customer_group'] ?? $row['group'] ?? null;
        if (!empty($groupName)) {
            $customerGroup = CustomerGroup::where('name', $groupName)->first();
            if ($customerGroup) {
                $data['customer_group_id'] = $customerGroup->id;
            }
        }

        $provinceName = $row['customer_province'] ?? $row['province'] ?? null;
        if (!empty($provinceName)) {
            $customerProvince = CustomerProvince::where('name', $provinceName)->first();
            if ($customerProvince) {
                $data['customer_province_id'] = $customerProvince->id;
            }
        }

        $zoneName = $row['customer_zone'] ?? $row['zone'] ?? null;
        if (!empty($zoneName)) {
            $customerZone = CustomerZone::where('name', $zoneName)->first();
            if ($customerZone) {
                $data['customer_zone_id'] = $customerZone->id;
            }
        }

        $paymentTermName = $row['payment_term'] ?? $row['payment_terms'] ?? null;
        if (!empty($paymentTermName)) {
            $paymentTerm = CustomerPaymentTerm::where('name', $paymentTermName)
                ->orWhere('days', $paymentTermName)
                ->first();
            if ($paymentTerm) {
                $data['customer_payment_term_id'] = $paymentTerm->id;
            }
        }

        return [
            'data' => $data,
            'starting_balance' => $startingBalance,
        ];
    }

    /**
     * Parse date from various formats
     */
    protected function parseDate($dateValue): ?string
    {
        if (empty($dateValue)) {
            return null;
        }

        try {
            // Handle Excel numeric date format
            if (is_numeric($dateValue)) {
                // Excel dates are stored as number of days since 1900-01-01
                $unix_date = ($dateValue - 25569) * 86400;
                return Carbon::createFromTimestamp($unix_date)->format('Y-m-d H:i:s');
            }

            // Handle short year format (d-m-y or d/m/y) - e.g., "27-03-25"
            // Assumes 2-digit year: 00-49 = 2000-2049, 50-99 = 1950-1999
            if (preg_match('/^(\d{1,2})[-\/](\d{1,2})[-\/](\d{2})$/', $dateValue, $matches)) {
                $day = str_pad($matches[1], 2, '0', STR_PAD_LEFT);
                $month = str_pad($matches[2], 2, '0', STR_PAD_LEFT);
                $year = $matches[3];

                // Convert 2-digit year to 4-digit (00-49 -> 2000-2049, 50-99 -> 1950-1999)
                $fullYear = ($year < 50) ? "20{$year}" : "19{$year}";

                // Parse as d-m-Y
                $dateString = "{$day}-{$month}-{$fullYear}";
                $date = Carbon::createFromFormat('d-m-Y', $dateString);
                if ($date !== false) {
                    return $date->format('Y-m-d H:i:s');
                }
            }

            // Try parsing common date formats
            $formats = [
                'Y-m-d H:i:s',  // 2025-12-22 10:30:00
                'Y-m-d',        // 2025-12-22
                'd-m-Y',        // 22-12-2025
                'd/m/Y',        // 22/12/2025
                'm-d-Y',        // 12-22-2025
                'm/d/Y',        // 12/22/2025
                'd-m-Y H:i:s',  // 22-12-2025 10:30:00
                'd/m/Y H:i:s',  // 22/12/2025 10:30:00
                'Y/m/d',        // 2025/12/22
            ];

            foreach ($formats as $format) {
                $date = Carbon::createFromFormat($format, $dateValue);
                if ($date !== false) {
                    return $date->format('Y-m-d H:i:s');
                }
            }

            // Try Carbon's flexible parser as fallback
            return Carbon::parse($dateValue)->format('Y-m-d H:i:s');
        } catch (\Exception $e) {
            // If date parsing fails, log and return null
            Log::warning("Failed to parse date: {$dateValue}", ['error' => $e->getMessage()]);
            return null;
        }
    }

    /**
     * Create credit/debit note for starting balance
     */
    protected function createStartingBalanceNote(Customer $customer, float $startingBalance, int $rowNumber): void
    {
        try {
            // Get default currency
            $defaultCurrencyId = Setting::get('general', 'default_currency', 1);
            if (!$defaultCurrencyId) {
                throw new \Exception('Default currency not configured in settings');
            }

            // Determine type and prefix based on balance
            // Positive balance = customer owes us = debit
            // Negative balance = we owe customer = credit
            $type = $startingBalance < 0 ? 'debit' : 'credit';
            $prefix = $startingBalance < 0 ? 'DBX' : 'CRX';
            $amount = abs($startingBalance);

            // Get currency rate (assuming default currency rate is 1)
            $currencyRate = 1.0;

            // Convert to USD
            $amountUsd = CurrencyHelper::toUsd($defaultCurrencyId, $amount, $currencyRate);

            // Create the credit/debit note
            CustomerCreditDebitNote::create([
                'date' => now(),
                'prefix' => $prefix,
                'type' => $type,
                'customer_id' => $customer->id,
                'currency_id' => $defaultCurrencyId,
                'currency_rate' => $currencyRate,
                'amount' => $amount,
                'amount_usd' => $amountUsd,
                'note' => 'Starting balance from customer import',
            ]);

        } catch (\Exception $e) {
            // Log error but don't fail the import
            $this->results['errors'][] = [
                'row' => $rowNumber,
                'error' => "Customer imported but starting balance note failed: " . $e->getMessage()
            ];
        }
    }

    /**
     * Clean numeric value by removing commas and converting to number
     */
    protected function cleanNumeric($value)
    {
        if ($value === null || $value === '') {
            return null;
        }

        // Remove commas, spaces, and other non-numeric characters (except decimal point and minus sign)
        $cleaned = preg_replace('/[^\d.\-]/', '', (string)$value);

        // Convert to float if it has decimal point, otherwise to int
        if (strpos($cleaned, '.') !== false) {
            return (float)$cleaned;
        }

        return $cleaned === '' ? 0 : (int)$cleaned;
    }

    /**
     * Batch size for bulk inserts
     */
    public function batchSize(): int
    {
        return 100;
    }

    /**
     * Chunk size for reading
     */
    public function chunkSize(): int
    {
        return 100;
    }

    /**
     * Get import results
     */
    public function getResults(): array
    {
        return $this->results;
    }
}
