<?php

namespace Database\Factories\Items;

use App\Models\Items\ItemAdjust;
use App\Models\Setups\Warehouse;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Items\ItemAdjust>
 */
class ItemAdjustFactory extends Factory
{
    protected $model = ItemAdjust::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Get a random warehouse
        $warehouse = Warehouse::inRandomOrder()->first();

        // If we don't have a warehouse, create one
        if (!$warehouse) {
            $warehouse = Warehouse::factory()->create();
        }

        return [
            // 'code' will be auto-generated by the model
            'date' => $this->faker->dateTimeBetween('-6 months', 'now'),
            'type' => $this->faker->randomElement(['Add', 'Subtract']),
            'warehouse_id' => $warehouse->id,
            'note' => $this->faker->optional(0.6)->sentence(),
            'created_by' => User::factory(),
            'updated_by' => function (array $attributes) {
                return $this->faker->boolean(30) ? User::factory() : $attributes['created_by'];
            },
        ];
    }

    /**
     * Item adjust with minimal required fields only
     */
    public function minimal(): static
    {
        return $this->state(fn (array $attributes) => [
            'note' => null,
        ]);
    }

    /**
     * Recent item adjust (last 30 days)
     */
    public function recent(): static
    {
        return $this->state(fn (array $attributes) => [
            'date' => $this->faker->dateTimeBetween('-30 days', 'now'),
        ]);
    }

    /**
     * Item adjust for a specific warehouse
     */
    public function forWarehouse(int $warehouseId): static
    {
        return $this->state(fn (array $attributes) => [
            'warehouse_id' => $warehouseId,
        ]);
    }

    /**
     * Item adjust with Add type
     */
    public function add(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'Add',
        ]);
    }

    /**
     * Item adjust with Subtract type
     */
    public function subtract(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'Subtract',
        ]);
    }
}
