<?php

namespace Database\Factories\Items;

use App\Models\Items\ItemTransfer;
use App\Models\Setups\Warehouse;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Items\ItemTransfer>
 */
class ItemTransferFactory extends Factory
{
    protected $model = ItemTransfer::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Get two different warehouses for transfer
        $warehouses = Warehouse::inRandomOrder()->take(2)->pluck('id');

        // If we don't have 2 warehouses, create them
        if ($warehouses->count() < 2) {
            $fromWarehouse = Warehouse::factory()->create();
            $toWarehouse = Warehouse::factory()->create();
        } else {
            $fromWarehouse = $warehouses->first();
            $toWarehouse = $warehouses->last();
        }

        return [
            // 'code' will be auto-generated by the model
            'date' => $this->faker->dateTimeBetween('-6 months', 'now'),
            'shipping_status' => $this->faker->randomElement(['Waiting', 'Shipped', 'Delivered']),
            'from_warehouse_id' => $fromWarehouse,
            'to_warehouse_id' => $toWarehouse,
            'note' => $this->faker->optional(0.6)->sentence(),
            'created_by' => User::factory(),
            'updated_by' => function (array $attributes) {
                return $this->faker->boolean(30) ? User::factory() : $attributes['created_by'];
            },
        ];
    }

    /**
     * Item transfer with minimal required fields only
     */
    public function minimal(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_status' => null,
            'note' => null,
        ]);
    }

    /**
     * Recent item transfer (last 30 days)
     */
    public function recent(): static
    {
        return $this->state(fn (array $attributes) => [
            'date' => $this->faker->dateTimeBetween('-30 days', 'now'),
        ]);
    }

    /**
     * Item transfer from a specific warehouse
     */
    public function fromWarehouse(int $warehouseId): static
    {
        return $this->state(function (array $attributes) use ($warehouseId) {
            // Make sure to_warehouse is different from from_warehouse
            $toWarehouse = Warehouse::where('id', '!=', $warehouseId)->inRandomOrder()->first();
            if (!$toWarehouse) {
                $toWarehouse = Warehouse::factory()->create();
            }

            return [
                'from_warehouse_id' => $warehouseId,
                'to_warehouse_id' => $toWarehouse->id,
            ];
        });
    }

    /**
     * Item transfer to a specific warehouse
     */
    public function toWarehouse(int $warehouseId): static
    {
        return $this->state(function (array $attributes) use ($warehouseId) {
            // Make sure from_warehouse is different from to_warehouse
            $fromWarehouse = Warehouse::where('id', '!=', $warehouseId)->inRandomOrder()->first();
            if (!$fromWarehouse) {
                $fromWarehouse = Warehouse::factory()->create();
            }

            return [
                'from_warehouse_id' => $fromWarehouse->id,
                'to_warehouse_id' => $warehouseId,
            ];
        });
    }

    /**
     * Waiting for shipment
     */
    public function waiting(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_status' => 'Waiting',
        ]);
    }

    /**
     * Shipped
     */
    public function shipped(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_status' => 'Shipped',
        ]);
    }

    /**
     * Delivered
     */
    public function delivered(): static
    {
        return $this->state(fn (array $attributes) => [
            'shipping_status' => 'Delivered',
        ]);
    }
}
